# Generated by Django 4.2.13 on 2025-02-09 06:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0015_alter_bookings_bookingstatus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payedOn", models.DateTimeField(blank=True, null=True)),
                (
                    "amountPaid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "amountOutstanding",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "totalAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("rejected", "rejected"),
                            ("completed", "completed"),
                            ("processing", "processing"),
                            ("paid", "paid"),
                            ("failed", "failed"),
                            ("reversed", "reversed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.bookings",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransactionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(1.0)],
                    ),
                ),
                ("external_reference", models.TextField(blank=True, default="")),
                ("authorization_url", models.TextField(blank=True, default="")),
                ("access_code", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("rejected", "rejected"),
                            ("completed", "completed"),
                            ("processing", "processing"),
                            ("paid", "paid"),
                            ("failed", "failed"),
                            ("reversed", "reversed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(choices=[("paystack", "Paystack")], max_length=30),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("card_payment", "Card_Payment"),
                            ("bank_account", "Cash_Account"),
                            ("bank_transfer", "Bank_Transfer"),
                        ],
                        default="card_payment",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("payed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.bookings",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoiceTransactions",
                        to="payments.transactioninvoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
