# Generated by Django 4.2.13 on 2025-02-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_transactioninvoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactioninvoice",
            name="invoiceId",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
