# Generated by Django 4.2.13 on 2025-02-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_transactioninvoice_invoiceid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactioninvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("rejected", "rejected"),
                    ("completed", "completed"),
                    ("processing", "processing"),
                    ("paid", "paid"),
                    ("failed", "failed"),
                    ("reversed", "reversed"),
                    ("success", "success"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transactionrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("rejected", "rejected"),
                    ("completed", "completed"),
                    ("processing", "processing"),
                    ("paid", "paid"),
                    ("failed", "failed"),
                    ("reversed", "reversed"),
                    ("success", "success"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
