# Generated by Django 4.2.13 on 2025-01-09 16:57

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(null=True, upload_to=account.models.User.upload_to),
        ),
    ]
