# Generated by Django 4.2.13 on 2025-01-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_remove_user_first_name_remove_user_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phoneNumber",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
