# Generated by Django 4.2.13 on 2025-01-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_role_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ManyToManyField(null=True, to="account.role"),
        ),
    ]
