# Generated by Django 4.2.13 on 2025-01-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0002_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="frequency",
        ),
    ]
