# Generated by Django 4.2.13 on 2025-01-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0004_alter_productcategory_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="tag",
        ),
    ]
