# Generated by Django 4.2.13 on 2025-01-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0005_remove_productcategory_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="tag",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="admin_dashboard.producttag"
            ),
        ),
    ]
