# Generated by Django 4.2.13 on 2025-01-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_dashboard",
            "0008_rename_categeoryaddition_additionalinformation_categoryaddition_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="additionalinformation",
            old_name="propertyStaus",
            new_name="propertyStatus",
        ),
    ]
