# Generated by Django 4.2.13 on 2025-01-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0010_blog_product_created_by_blogimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="productStatus",
            field=models.CharField(
                choices=[("sales", "sales"), ("rent", "rent")],
                default="rent",
                max_length=100,
            ),
        ),
    ]
