# Generated by Django 4.2.13 on 2025-01-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0011_product_productstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="additionalinformation",
            name="propertyStatus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "Available"),
                    ("sold", "Sold"),
                    ("rented", "Rented"),
                    ("reserved", "Reserved"),
                    ("not_available", "Not Available"),
                ],
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(
                choices=[("Property", "Property"), ("Appartment", "Appartment")],
                max_length=100,
            ),
        ),
    ]
