# Generated by Django 4.2.13 on 2025-01-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_dashboard",
            "0013_remove_additionalinformation_propertystatus_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="specification",
            name="categorySpecification",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="shortDescription",
            new_name="sqft",
        ),
        migrations.RemoveField(
            model_name="product",
            name="propertyStatus",
        ),
        migrations.AddField(
            model_name="product",
            name="bathroom",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="bedroom",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="buildYear",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="packing",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="yes", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="productCategory",
            field=models.CharField(
                blank=True,
                choices=[("for sales", "For Sales"), ("shortlet", "Shortlet")],
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="productStatus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "Available"),
                    ("sold", "Sold"),
                    ("rented", "Rented"),
                    ("reserved", "Reserved"),
                    ("not_available", "Not Available"),
                    ("completed", "Completed"),
                    ("coming soon", "Coming Soon"),
                ],
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="productType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("apartment", "Apartment"),
                    ("villa", "Villa"),
                    ("duplex", "Duplex"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(blank=True, to="admin_dashboard.producttag"),
        ),
        migrations.DeleteModel(
            name="AdditionalInformation",
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
        migrations.DeleteModel(
            name="Specification",
        ),
    ]
