# Generated by Django 4.2.13 on 2025-01-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0015_blogtag_blog_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="productStatus",
            field=models.CharField(
                blank=True,
                choices=[
                    ("available", "Available"),
                    ("sold", "Sold"),
                    ("rented", "Rented"),
                    ("reserved", "Reserved"),
                    ("not_available", "Not Available"),
                    ("completed", "Completed"),
                    ("ongoing", "Ongoing"),
                    ("coming soon", "Coming Soon"),
                ],
                max_length=500,
                null=True,
            ),
        ),
    ]
