# Generated by Django 4.2.13 on 2025-01-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0016_alter_product_productstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_by",
        ),
    ]
