# Generated by Django 4.2.13 on 2025-01-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_dashboard",
            "0018_country_productstatus_producttype_state_localgovt_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productCity",
                to="admin_dashboard.localgovt",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productCountry",
                to="admin_dashboard.country",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="productStatus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="admin_dashboard.productstatus",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="productType",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productTypes",
                to="admin_dashboard.producttype",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productState",
                to="admin_dashboard.state",
            ),
        ),
    ]
