# Generated by Django 4.2.13 on 2025-01-17 22:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0020_product_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitors",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("count", models.BigIntegerField(default=1)),
                ("month", models.CharField(max_length=20, null=True)),
                ("year", models.CharField(max_length=7, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
