# Generated by Django 4.2.13 on 2025-02-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0021_visitors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yearly", "yearly"),
                    ("monthly", "monthly"),
                    ("daily", "daily"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
