# Generated by Django 4.2.13 on 2025-01-13 14:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_dashboard", "0015_blogtag_blog_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phoneNumber", models.CharField(blank=True, max_length=20, null=True)),
                ("title", models.CharField(max_length=20, null=True)),
                ("firstName", models.CharField(max_length=225, null=True)),
                ("lastName", models.CharField(max_length=225, null=True)),
                ("dateOfBirth", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "bookingStatus",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("rejected", "rejected"),
                            ("completed", "completed"),
                            ("processing", "processing"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("specialRequest", models.TextField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admin_dashboard.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
