# Generated by Django 4.2.13 on 2025-01-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="location",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
