# Generated by Django 4.2.13 on 2025-01-13 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_bookings_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("firstName", models.CharField(max_length=225, null=True)),
                ("lastName", models.CharField(max_length=225, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phoneNumber", models.CharField(max_length=225, null=True)),
                ("message", models.TextField(null=True)),
                ("inquiryType", models.CharField(max_length=225, null=True)),
                ("aboutUs", models.CharField(max_length=500, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
