# Generated by Django 4.2.13 on 2025-01-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookings",
            name="initiated_by",
        ),
    ]
