# Generated by Django 4.2.13 on 2025-01-13 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0016_alter_product_productstatus"),
        ("properties", "0006_remove_bookings_initiated_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogViews",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("count", models.BigIntegerField(default=0)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="admin_dashboard.blog",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
