# Generated by Django 4.2.13 on 2025-01-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0008_bookings_initiated_by_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="bookingStatus",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("rejected", "rejected"),
                    ("completed", "completed"),
                    ("processing", "processing"),
                    ("paid", "paid"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
