# Generated by Django 4.2.13 on 2025-01-17 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0021_visitors"),
        ("properties", "0009_alter_bookings_bookingstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="admin_dashboard.blog",
            ),
        ),
    ]
