# Generated by Django 4.2.13 on 2025-01-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_alter_comment_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="contactMethod",
            field=models.CharField(
                choices=[("in_person", "In_Person"), ("virtual", "Virtual")],
                default="in_person",
                max_length=100,
            ),
        ),
    ]
