# Generated by Django 4.2.13 on 2025-01-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_alter_appointment_contactmethod"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="firstName",
            new_name="fullName",
        ),
        migrations.RemoveField(
            model_name="bookings",
            name="address",
        ),
        migrations.RemoveField(
            model_name="bookings",
            name="country",
        ),
        migrations.RemoveField(
            model_name="bookings",
            name="dateOfBirth",
        ),
        migrations.RemoveField(
            model_name="bookings",
            name="lastName",
        ),
        migrations.RemoveField(
            model_name="bookings",
            name="location",
        ),
        migrations.RemoveField(
            model_name="bookings",
            name="title",
        ),
        migrations.AddField(
            model_name="bookings",
            name="adultsCount",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bookings",
            name="checkInDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="checkOutDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="bookings",
            name="childrenCount",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bookings",
            name="infantsCount",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bookings",
            name="petCount",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bookings",
            name="stayDuration",
            field=models.BigIntegerField(default=0),
        ),
    ]
