# Generated by Django 4.2.13 on 2025-01-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_rename_firstname_bookings_fullname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="confirmationNumber",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
