# Generated by Django 4.2.13 on 2025-02-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0014_comment_createdby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="bookingStatus",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("rejected", "rejected"),
                    ("completed", "completed"),
                    ("processing", "processing"),
                    ("paid", "paid"),
                    ("failed", "failed"),
                    ("reversed", "reversed"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
